[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:mariadb]
command=/usr/sbin/mariadbd --user=mysql
autostart=true
autorestart=true
priority=1
stdout_logfile=/var/log/supervisor/mariadb.log
stderr_logfile=/var/log/supervisor/mariadb_err.log

[program:asterisk]
command=/usr/sbin/asterisk -f -U asterisk -G asterisk -vvv
autostart=true
autorestart=true
priority=2
startsecs=5
stdout_logfile=/var/log/supervisor/asterisk.log
stderr_logfile=/var/log/supervisor/asterisk_err.log

[program:apache2]
command=/usr/sbin/apachectl -D FOREGROUND
autostart=true
autorestart=true
priority=3
stdout_logfile=/var/log/supervisor/apache2.log
stderr_logfile=/var/log/supervisor/apache2_err.log
